kind: Service
apiVersion: v1
metadata:
  name: {{ .Chart.Name | trimSuffix "-chart" }}-service
spec:
  selector:
    {{- include "postgres-chart.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}