apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Chart.Name | trimSuffix "-chart" }}-deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "notejam-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "notejam-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name | trimSuffix "-chart" }}-con
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password

            - name: POSTGRES_HOST
              value: postgres-service

          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
