apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name | trimSuffix "-chart" }}-service
spec:
  selector:
    {{- include "notejam-chart.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: "TCP"
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}